$home = /home/$USER
$walldir = $home/Wallpapers
$rwallpaper = $home/Git/dotfiles/scripts/rwallpaper.sh
$default_wallpaper = $walldir/wallhaven-4v2675.jpg

general {
    hide_cursor = false
    ignore_empty_input = true
    
    fail_timeout = 2000 # 2 seconds
}

auth {
    fingerprint {
        enabled = true
    }
}

animations {
    enabled = true
}

background {
    path = $default_wallpaper
    color = rgba(17, 17, 17, 1.0)

    blur_passes = 1
    blur_size = 3
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.05

    reload_time = 10
    reload_cmd = $rwallpaper
    crossfade_time = 5.0
    zindex = -1
}

image {
    path = $default_wallpaper
    size = 150
    rounding = -1 # negetive value => circle

    border_size = 4
    border_color = rgba(221, 221, 221, 1.0)

    reload_time = 10
    reload_cmd = $rwallpaper

    position = 0, 200
    halign = center
    valign = center

    shadow_passes = 1
    #onclick = 
}

# shape {
#     monitor =
#     size = 360, 60
#     color = rgba(0, 0, 0, 0.0) # no fill
#     rounding = -1 # circle
#     border_size = 4
#     border_color = rgba(0, 207, 230, 1.0)
# 
#     position = 0, 80
#     halign = center
#     valign = center
# }

input-field {
    size = 20%, 5%
    outline_thickness = 4
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    font_family = JetBrainsMono Nerd Font Mono
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}
