source = ~/.config/hypr/confs/monitors.conf
source = ~/.config/hypr/confs/autostart.conf
source = ~/.config/hypr/confs/env.conf
source = ~/.config/hypr/confs/permissions.conf
source = ~/.config/hypr/confs/general.conf
source = ~/.config/hypr/confs/decoration.conf
source = ~/.config/hypr/confs/animation.conf
source = ~/.config/hypr/confs/workspace-rules.conf
source = ~/.config/hypr/confs/layouts.conf
source = ~/.config/hypr/confs/input.conf
source = ~/.config/hypr/confs/gestures.conf
source = ~/.config/hypr/confs/devices.conf
source = ~/.config/hypr/confs/bindings.conf
source = ~/.config/hypr/confs/window-rules.conf
