# Input

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        disable_while_typing = true
        natural_scroll = true
        middle_button_emulation = true
        drag_lock = 0
        flip_x = false
        flip_y = false
        drag_3fg = 0

        # present in doc, but hyprland gives error
        # clickfinger_behaviour = false
        # tap_to_click = true
        # tap_and_drag = true
    }
}
