# Variables

$terminal = alacritty
$fileManager = dolphin
$menu = wofi --gtk-dark --allow-images --allow-markup --show drun -p "Open an application"
$menu2 = wofi --gtk-dark --show run -p "Run a command"
$mainMod = SUPER

$rhyprpaper = ~/Git/dotfiles/scripts/rhyprpaper.sh
