# Window rules

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppress_event maximize, class:.*
windowrule = match:class *, suppress_event maximize

# Fix some dragging issues with XWayland
# windowrule = no_focus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# windowrule = opacity 0.9 override 0.7 override 1.0 override, class:Alacritty
windowrule = match:class Alacritty, opacity 0.9 override 0.7 override 1.0 override
