# Misc

misc {
    animate_manual_resizes = true
    animate_mouse_windowdragging = true

    enable_swallow = true
    swallow_regex = Alacritty|kitty
    swallow_exception_regex = [wx]ev
    
    focus_on_activate = false

    close_special_on_empty = true

    exit_window_retains_fullscreen = false

    initial_workspace_tracking = 1

    middle_click_paste = true
}
