hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
    disabled = false,
    transform = 0,
    mirror = "",
    bitdepth = 8,
    cm = "srgb",
    sdr_eotf = "default",
    sdrbrightness = 1.0,
    sdrsaturation = 1.0,
    vrr = 0,
    -- icc = "",
    reserved_area = 0,
    supports_wide_color = 0,
    supports_hdr = 0,
    sdr_min_luminance = 0.2,
    sdr_max_luminance = 80,
    min_luminance = -1,
    max_luminance = -1,
    max_avg_luminance = -1,
})
