# Variables

# $terminal = alacritty
$terminal = kitty
$fileManager = dolphin
$menu = wofi --allow-images --allow-markup --show drun -p "Open an application"
$menu2 = sh -c "$(wofi --dmenu)"
$mainMod = SUPER

$rhyprpaper = ~/.local/bin/rhyprpaper.sh
